name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  backend:
    name: Backend CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build and test with Maven
        run: |
          cd backend
          mvn --batch-mode package

  frontend:
    name: Frontend CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          cd frontend
          npm ci
      - name: Build
        run: |
          cd frontend
          npm run build

  mediasoup:
    name: Mediasoup CI
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
      - name: Set up node 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: |
          cd mediasoup
          npm ci --ignore-scripts
      - name: Build
        run: |
          cd mediasoup
          npm run build